[general]
  logger_level = "debug"

[dns]
  servers = ["8.8.8.8", "114.114.114.114"]

[[listener]]
  typ = "http"
  addr = ":8081"
  [listener.params]
    auth_type = "basic"
    password = "123123"
    user = "root"

[[listener]]
  typ = "socks"
  addr = ":9000"
  [listener.params]
    auth_type = "basic"
    password = "123"
    user = "root"

[server_group]
  Proxy = {typ = "select", servers = ["DIRECT"]}

[[rule]]
  typ = "DOMAIN"
  value = "google.com"
  proxy = "Proxy"
  [rule.params]
    Comment = "search engine"

[[rule]]
  typ = "DOMAIN"
  value = "github.com"
  proxy = "Proxy"
  [rule.params]
    Comment = "source code"

[[rule]]
  typ = "FINAL"
  proxy = "Proxy"
