[general]
  logger_level = "debug"
  default_test_uri = "http://www.bing.com"

[dns]
  servers = ["10.150.33.9"]
  [[dns.mapping]]
    domain = "localhost"
    ip = ["127.0.0.1"]

[controller]
  addr = ":9001"

[[listener]]
  typ = "http"
  addr = ":8081"

[[listener]]
  typ = "socks"
  addr = ":9000"

[server]
  surge = {typ = "socks5", host = "localhost", port = 8889}

[server_group]
  Proxy = {typ = "select", servers = ["DIRECT"]}
  AdBlock = {typ = "select", servers = ["REJECT"]}
  Domestic = {typ = "select", servers = ["DIRECT"]}

[[rule]]
  typ = "DOMAIN"
  value = "google.com"
  proxy = "Proxy"
  [rule.params]
    Comment = "search engine"

[[rule]]
  typ = "DOMAIN"
  value = "github.com"
  proxy = "Proxy"
  [rule.params]
    Comment = "source code"

[[rule]]
  typ = "RULE-SET"
  value = "$1"
  proxy = "Proxy"
  [rule.params]
    url = "https://raw.githubusercontent.com/lhie1/Rules/master/Surge3/Proxy.list"

[[rule]]
  typ = "RULE-SET"
  value = "$1"
  proxy = "AdBlock"
  [rule.params]
    url = "https://raw.githubusercontent.com/lhie1/Rules/master/Surge3/Reject.list"

[[rule]]
  typ = "RULE-SET"
  value = "$1"
  proxy = "Proxy"
  [rule.params]
    url = "https://raw.githubusercontent.com/lhie1/Rules/master/Surge3/AsianTV.list"

[[rule]]
  typ = "RULE-SET"
  value = "$1"
  proxy = "Proxy"
  [rule.params]
    url = "https://raw.githubusercontent.com/lhie1/Rules/master/Surge3/GlobalTV.list"

[[rule]]
  typ = "RULE-SET"
  value = "https://raw.githubusercontent.com/lhie1/Rules/master/Surge3/Proxy.list"
  proxy = "Proxy"

[[rule]]
  typ = "RULE-SET"
  value = "https://raw.githubusercontent.com/lhie1/Rules/master/Surge3/Proxy.list"
  proxy = "Proxy"

[[rule]]
  typ = "FINAL"
  proxy = "Proxy"
